/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-11 at 01:28:24 UTC 
 * Modify at your own risk.
 */

package com.appspot.cenplusplus.cenplusplus.model;

/**
 * Model definition for HelloRainLocation.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the cenplusplus. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HelloRainLocation extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isRaining;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rainStatus;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsRaining() {
    return isRaining;
  }

  /**
   * @param isRaining isRaining or {@code null} for none
   */
  public HelloRainLocation setIsRaining(java.lang.Boolean isRaining) {
    this.isRaining = isRaining;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public HelloRainLocation setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRainStatus() {
    return rainStatus;
  }

  /**
   * @param rainStatus rainStatus or {@code null} for none
   */
  public HelloRainLocation setRainStatus(java.lang.String rainStatus) {
    this.rainStatus = rainStatus;
    return this;
  }

  @Override
  public HelloRainLocation set(String fieldName, Object value) {
    return (HelloRainLocation) super.set(fieldName, value);
  }

  @Override
  public HelloRainLocation clone() {
    return (HelloRainLocation) super.clone();
  }

}
