/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-11 at 01:28:24 UTC 
 * Modify at your own risk.
 */

package com.appspot.cenplusplus.cenplusplus.model;

/**
 * Model definition for HelloGardenRecord.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the cenplusplus. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HelloGardenRecord extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long heatIndex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long humidity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long moistureLevel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long temperature;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getHeatIndex() {
    return heatIndex;
  }

  /**
   * @param heatIndex heatIndex or {@code null} for none
   */
  public HelloGardenRecord setHeatIndex(java.lang.Long heatIndex) {
    this.heatIndex = heatIndex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getHumidity() {
    return humidity;
  }

  /**
   * @param humidity humidity or {@code null} for none
   */
  public HelloGardenRecord setHumidity(java.lang.Long humidity) {
    this.humidity = humidity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMoistureLevel() {
    return moistureLevel;
  }

  /**
   * @param moistureLevel moistureLevel or {@code null} for none
   */
  public HelloGardenRecord setMoistureLevel(java.lang.Long moistureLevel) {
    this.moistureLevel = moistureLevel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTemperature() {
    return temperature;
  }

  /**
   * @param temperature temperature or {@code null} for none
   */
  public HelloGardenRecord setTemperature(java.lang.Long temperature) {
    this.temperature = temperature;
    return this;
  }

  @Override
  public HelloGardenRecord set(String fieldName, Object value) {
    return (HelloGardenRecord) super.set(fieldName, value);
  }

  @Override
  public HelloGardenRecord clone() {
    return (HelloGardenRecord) super.clone();
  }

}
