/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-11 at 01:28:24 UTC 
 * Modify at your own risk.
 */

package com.appspot.cenplusplus.cenplusplus.model;

/**
 * Model definition for HelloValidUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the cenplusplus. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HelloValidUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("email_error")
  private java.lang.String emailError;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("password_error")
  private java.lang.String passwordError;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("username_error")
  private java.lang.String usernameError;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailError() {
    return emailError;
  }

  /**
   * @param emailError emailError or {@code null} for none
   */
  public HelloValidUser setEmailError(java.lang.String emailError) {
    this.emailError = emailError;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPasswordError() {
    return passwordError;
  }

  /**
   * @param passwordError passwordError or {@code null} for none
   */
  public HelloValidUser setPasswordError(java.lang.String passwordError) {
    this.passwordError = passwordError;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsernameError() {
    return usernameError;
  }

  /**
   * @param usernameError usernameError or {@code null} for none
   */
  public HelloValidUser setUsernameError(java.lang.String usernameError) {
    this.usernameError = usernameError;
    return this;
  }

  @Override
  public HelloValidUser set(String fieldName, Object value) {
    return (HelloValidUser) super.set(fieldName, value);
  }

  @Override
  public HelloValidUser clone() {
    return (HelloValidUser) super.clone();
  }

}
